### ISSUE TITLE
Failed to install on mac m1

### ISSUE THREAD

**Issue by rizkyramadhan** [SergeyFromHell/node-mdbx#5]
npm ERR! code 1
npm ERR! path /Users/riz/Documents/base/node_modules/node-mdbx
npm ERR! command failed
npm ERR! command sh -c node build.js
npm ERR! [
npm ERR!   '/Users/riz/.fnm/node-versions/v16.4.0/installation/bin/node',
npm ERR!   '/Users/riz/Documents/base/node_modules/.bin/cmake-js',
npm ERR!   'rebuild'
npm ERR! ]
npm ERR! Not searching for unused variables given on the command line.
npm ERR! -- The C compiler identification is AppleClang 12.0.5.12050022
npm ERR! -- The CXX compiler identification is AppleClang 12.0.5.12050022
npm ERR! -- Detecting C compiler ABI info
npm ERR! -- Detecting C compiler ABI info - done
npm ERR! -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
npm ERR! -- Detecting C compile features
npm ERR! -- Detecting C compile features - done
npm ERR! -- Detecting CXX compiler ABI info
npm ERR! -- Detecting CXX compiler ABI info - done
npm ERR! -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
npm ERR! -- Detecting CXX compile features
npm ERR! -- Detecting CXX compile features - done
npm ERR! -- Configuring done
npm ERR! -- Generating done
npm ERR! -- Build files have been written to: /Users/riz/Documents/base/node_modules/node-mdbx/build
npm ERR! [ 16%] Building C object CMakeFiles/node-mdbx-native.dir/deps/mdbx/mdbx.c.o
npm ERR! [ 33%] Building CXX object CMakeFiles/node-mdbx-native.dir/src/bindings.cc.o
npm ERR! info TOOL Using Unix Makefiles generator.
npm ERR! info CMD CLEAN
npm ERR! info RUN [
npm ERR! info RUN   'cmake',
npm ERR! info RUN   '-E',
npm ERR! info RUN   'remove_directory',
npm ERR! info RUN   '/Users/riz/Documents/base/node_modules/node-mdbx/build'
npm ERR! info RUN ]
npm ERR! info CMD CONFIGURE
npm ERR! info RUN [
npm ERR! info RUN   'cmake',
npm ERR! info RUN   '/Users/riz/Documents/base/node_modules/node-mdbx',
npm ERR! info RUN   '--no-warn-unused-cli',
npm ERR! info RUN   '-G',
npm ERR! info RUN   'Unix Makefiles',
npm ERR! info RUN   '-DCMAKE_JS_VERSION=6.1.4',
npm ERR! info RUN   '-DCMAKE_BUILD_TYPE=Release',
npm ERR! info RUN   '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/riz/Documents/base/node_modules/node-mdbx/build/Release',
npm ERR! info RUN   '-DCMAKE_JS_INC=/Users/riz/.cmake-js/node-arm64/v16.4.0/include/node',
npm ERR! info RUN   '-DCMAKE_JS_SRC=',
npm ERR! info RUN   '-DNODE_RUNTIME=node',
npm ERR! info RUN   '-DNODE_RUNTIMEVERSION=16.4.0',
npm ERR! info RUN   '-DNODE_ARCH=arm64',
npm ERR! info RUN   '-DCMAKE_CXX_FLAGS=-D_DARWIN_USE_64_BIT_INODE=1 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DBUILDING_NODE_EXTENSION',
npm ERR! info RUN   '-DCMAKE_SHARED_LINKER_FLAGS=-undefined dynamic_lookup'
npm ERR! info RUN ]
npm ERR! CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
npm ERR!   Compatibility with CMake < 2.8.12 will be removed from a future version of
npm ERR!   CMake.
npm ERR! 
npm ERR!   Update the VERSION argument <min> value or use a ...<max> suffix to tell
npm ERR!   CMake that the project does not need compatibility with older versions.
npm ERR! 
npm ERR! 
npm ERR! CMake Warning (dev):
npm ERR!   Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
npm ERR!   --help-policy CMP0042" for policy details.  Use the cmake_policy command to
npm ERR!   set the policy and suppress this warning.
npm ERR! 
npm ERR!   MACOSX_RPATH is not specified for the following targets:
npm ERR! 
npm ERR!    node-mdbx-native
npm ERR! 
npm ERR! This warning is for project developers.  Use -Wno-dev to suppress it.
npm ERR! 
npm ERR! info CMD BUILD
npm ERR! info RUN [
npm ERR! info RUN   'cmake',
npm ERR! info RUN   '--build',
npm ERR! info RUN   '/Users/riz/Documents/base/node_modules/node-mdbx/build',
npm ERR! info RUN   '--config',
npm ERR! info RUN   'Release'
npm ERR! info RUN ]
npm ERR! In file included from /Users/riz/Documents/base/node_modules/node-mdbx/src/bindings.cc:1:
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:140:7: warning: alias declarations are a C++11 extension [-Wc++11-extensions]
npm ERR!       TypedArrayOf<int8_t>;  ///< Typed-array of signed 8-bit integers
npm ERR!       ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:142:7: warning: alias declarations are a C++11 extension [-Wc++11-extensions]
npm ERR!       TypedArrayOf<uint8_t>;  ///< Typed-array of unsigned 8-bit integers
npm ERR!       ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:144:7: warning: alias declarations are a C++11 extension [-Wc++11-extensions]
npm ERR!       TypedArrayOf<int16_t>;  ///< Typed-array of signed 16-bit integers
npm ERR!       ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:146:7: warning: alias declarations are a C++11 extension [-Wc++11-extensions]
npm ERR!       TypedArrayOf<uint16_t>;  ///< Typed-array of unsigned 16-bit integers
npm ERR!       ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:148:7: warning: alias declarations are a C++11 extension [-Wc++11-extensions]
npm ERR!       TypedArrayOf<int32_t>;  ///< Typed-array of signed 32-bit integers
npm ERR!       ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:150:7: warning: alias declarations are a C++11 extension [-Wc++11-extensions]
npm ERR!       TypedArrayOf<uint32_t>;  ///< Typed-array of unsigned 32-bit integers
npm ERR!       ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:152:7: warning: alias declarations are a C++11 extension [-Wc++11-extensions]
npm ERR!       TypedArrayOf<float>;  ///< Typed-array of 32-bit floating-point values
npm ERR!       ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:154:7: warning: alias declarations are a C++11 extension [-Wc++11-extensions]
npm ERR!       TypedArrayOf<double>;  ///< Typed-array of 64-bit floating-point values
npm ERR!       ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:157:7: warning: alias declarations are a C++11 extension [-Wc++11-extensions]
npm ERR!       TypedArrayOf<int64_t>;  ///< Typed array of signed 64-bit integers
npm ERR!       ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:159:7: warning: alias declarations are a C++11 extension [-Wc++11-extensions]
npm ERR!       TypedArrayOf<uint64_t>;  ///< Typed array of unsigned 64-bit integers
npm ERR!       ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:164:34: warning: alias declarations are a C++11 extension [-Wc++11-extensions]
npm ERR!   using ModuleRegisterCallback = Object (*)(Env env, Object exports);
npm ERR!                                  ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:207:45: warning: alias declarations are a C++11 extension [-Wc++11-extensions]
npm ERR!     template <typename T> using Finalizer = void (*)(Env, T*);
npm ERR!                                             ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:208:65: error: a space is required between consecutive right angle brackets (use '> >')
npm ERR!     template <typename T, Finalizer<T> fini = Env::DefaultFini<T>>
npm ERR!                                                                 ^~
npm ERR!                                                                 > >
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:208:40: warning: default template arguments for a function template are a C++11 extension [-Wc++11-extensions]
npm ERR!     template <typename T, Finalizer<T> fini = Env::DefaultFini<T>>
npm ERR!                                        ^      ~~~~~~~~~~~~~~~~~~~
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:212:31: warning: alias declarations are a C++11 extension [-Wc++11-extensions]
npm ERR!     using FinalizerWithHint = void (*)(Env, DataType*, HintType*);
npm ERR!                               ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:216:60: error: a space is required between consecutive right angle brackets (use '> >')
npm ERR!                 Env::DefaultFiniWithHint<DataType, HintType>>
npm ERR!                                                            ^~
npm ERR!                                                            > >
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:215:53: warning: default template arguments for a function template are a C++11 extension [-Wc++11-extensions]
npm ERR!               FinalizerWithHint<DataType, HintType> fini =
npm ERR!                                                     ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:569:26: warning: deleted function definitions are a C++11 extension [-Wc++11-extensions]
npm ERR!       PropertyLValue() = delete;
npm ERR!                          ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:751:20: error: no template named 'initializer_list' in namespace 'std'
npm ERR!         const std::initializer_list<PropertyDescriptor>& properties
npm ERR!               ~~~~~^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:916:5: error: unknown type name 'constexpr'
npm ERR!     constexpr
npm ERR!     ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:918:5: warning: variable templates are a C++14 extension [-Wc++14-extensions]
npm ERR!     napi_typedarray_type TypedArrayTypeForPrimitiveType() {
npm ERR!     ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:918:25: error: expected ';' at end of declaration list
npm ERR!     napi_typedarray_type TypedArrayTypeForPrimitiveType() {
npm ERR!                         ^
npm ERR!                         ;
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:954:8: error: unknown type name 'napi_typedarray_type'; did you mean '::napi_typedarray_type'?
npm ERR!        napi_typedarray_type type =
npm ERR!        ^~~~~~~~~~~~~~~~~~~~
npm ERR!        ::napi_typedarray_type
npm ERR! /Users/riz/.cmake-js/node-arm64/v16.4.0/include/node/js_native_api_types.h:71:3: note: '::napi_typedarray_type' declared here
npm ERR! } napi_typedarray_type;
npm ERR!   ^
npm ERR! In file included from /Users/riz/Documents/base/node_modules/node-mdbx/src/bindings.cc:1:
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:977:8: error: unknown type name 'napi_typedarray_type'; did you mean '::napi_typedarray_type'?
npm ERR!        napi_typedarray_type type =
npm ERR!        ^~~~~~~~~~~~~~~~~~~~
npm ERR!        ::napi_typedarray_type
npm ERR! /Users/riz/.cmake-js/node-arm64/v16.4.0/include/node/js_native_api_types.h:71:3: note: '::napi_typedarray_type' declared here
npm ERR! } napi_typedarray_type;
npm ERR!   ^
npm ERR! In file included from /Users/riz/Documents/base/node_modules/node-mdbx/src/bindings.cc:1:
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:1010:18: error: unknown type name 'napi_typedarray_type'; did you mean '::napi_typedarray_type'?
npm ERR!                  napi_typedarray_type type,
npm ERR!                  ^~~~~~~~~~~~~~~~~~~~
npm ERR!                  ::napi_typedarray_type
npm ERR! /Users/riz/.cmake-js/node-arm64/v16.4.0/include/node/js_native_api_types.h:71:3: note: '::napi_typedarray_type' declared here
npm ERR! } napi_typedarray_type;
npm ERR!   ^
npm ERR! In file included from /Users/riz/Documents/base/node_modules/node-mdbx/src/bindings.cc:1:
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:955:24: error: no member named 'TypedArrayTypeForPrimitiveType' in 'Napi::TypedArray'
npm ERR!            TypedArray::TypedArrayTypeForPrimitiveType<T>()
npm ERR!            ~~~~~~~~~~~~^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:955:55: error: 'T' does not refer to a value
npm ERR!            TypedArray::TypedArrayTypeForPrimitiveType<T>()
npm ERR!                                                       ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:940:22: note: declared here
npm ERR!   template <typename T>
npm ERR!                      ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:955:58: error: expected expression
npm ERR!            TypedArray::TypedArrayTypeForPrimitiveType<T>()
npm ERR!                                                          ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:978:24: error: no member named 'TypedArrayTypeForPrimitiveType' in 'Napi::TypedArray'
npm ERR!            TypedArray::TypedArrayTypeForPrimitiveType<T>()
npm ERR!            ~~~~~~~~~~~~^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:978:55: error: 'T' does not refer to a value
npm ERR!            TypedArray::TypedArrayTypeForPrimitiveType<T>()
npm ERR!                                                       ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:940:22: note: declared here
npm ERR!   template <typename T>
npm ERR!                      ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:978:58: error: expected expression
npm ERR!            TypedArray::TypedArrayTypeForPrimitiveType<T>()
npm ERR!                                                          ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:1070:25: warning: alias declarations are a C++11 extension [-Wc++11-extensions]
npm ERR!    using VoidCallback = void (*)(const CallbackInfo& info);
npm ERR!                         ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:1071:21: warning: alias declarations are a C++11 extension [-Wc++11-extensions]
npm ERR!    using Callback = Value (*)(const CallbackInfo& info);
npm ERR!                     ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:1111:32: error: no template named 'initializer_list' in namespace 'std'
npm ERR!    Value operator()(const std::initializer_list<napi_value>& args) const;
npm ERR!                           ~~~~~^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:1113:26: error: no template named 'initializer_list' in namespace 'std'
npm ERR!    Value Call(const std::initializer_list<napi_value>& args) const;
npm ERR!                     ~~~~~^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:1117:26: error: no template named 'initializer_list' in namespace 'std'
npm ERR!               const std::initializer_list<napi_value>& args) const;
npm ERR!                     ~~~~~^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:1122:34: error: no template named 'initializer_list' in namespace 'std'
npm ERR!                       const std::initializer_list<napi_value>& args,
npm ERR!                             ~~~~~^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:1132:26: error: no template named 'initializer_list' in namespace 'std'
npm ERR!    Object New(const std::initializer_list<napi_value>& args) const;
npm ERR!                     ~~~~~^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:1207:27: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
npm ERR!     Reference(Reference<T>&& other);
npm ERR!                           ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:1208:42: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
npm ERR!     Reference<T>& operator =(Reference<T>&& other);
npm ERR!                                          ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:1209:5: warning: deleted function definitions are a C++11 extension [-Wc++11-extensions]
npm ERR!     NAPI_DISALLOW_ASSIGN(Reference<T>)
npm ERR!     ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:94:69: note: expanded from macro 'NAPI_DISALLOW_ASSIGN'
npm ERR! # define NAPI_DISALLOW_ASSIGN(CLASS) void operator=(const CLASS&) = delete;
npm ERR!                                                                     ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:1252:38: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
npm ERR!     ObjectReference(Reference<Object>&& other);
npm ERR!                                      ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:1253:50: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
npm ERR!     ObjectReference& operator =(Reference<Object>&& other);
npm ERR!                                                  ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:1254:36: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
npm ERR!     ObjectReference(ObjectReference&& other);
npm ERR!                                    ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:1255:48: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
npm ERR!     ObjectReference& operator =(ObjectReference&& other);
npm ERR!                                                ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:1256:5: warning: deleted function definitions are a C++11 extension [-Wc++11-extensions]
npm ERR!     NAPI_DISALLOW_ASSIGN(ObjectReference)
npm ERR!     ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:94:69: note: expanded from macro 'NAPI_DISALLOW_ASSIGN'
npm ERR! # define NAPI_DISALLOW_ASSIGN(CLASS) void operator=(const CLASS&) = delete;
npm ERR!                                                                     ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:1289:42: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
npm ERR!     FunctionReference(Reference<Function>&& other);
npm ERR!                                          ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:1290:54: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
npm ERR!     FunctionReference& operator =(Reference<Function>&& other);
npm ERR!                                                      ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:1291:40: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
npm ERR!     FunctionReference(FunctionReference&& other);
npm ERR!                                        ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:1292:52: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
npm ERR!     FunctionReference& operator =(FunctionReference&& other);
npm ERR!                                                    ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:1293:5: warning: deleted function definitions are a C++11 extension [-Wc++11-extensions]
npm ERR!     NAPI_DISALLOW_ASSIGN_COPY(FunctionReference)
npm ERR!     ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:98:5: note: expanded from macro 'NAPI_DISALLOW_ASSIGN_COPY'
npm ERR!     NAPI_DISALLOW_ASSIGN(CLASS)           \
npm ERR!     ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:94:69: note: expanded from macro 'NAPI_DISALLOW_ASSIGN'
npm ERR! # define NAPI_DISALLOW_ASSIGN(CLASS) void operator=(const CLASS&) = delete;
npm ERR!                                                                     ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:1293:5: warning: deleted function definitions are a C++11 extension [-Wc++11-extensions]
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:99:5: note: expanded from macro 'NAPI_DISALLOW_ASSIGN_COPY'
npm ERR!     NAPI_DISALLOW_COPY(CLASS)
npm ERR!     ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:95:58: note: expanded from macro 'NAPI_DISALLOW_COPY'
npm ERR! # define NAPI_DISALLOW_COPY(CLASS) CLASS(const CLASS&) = delete;
npm ERR!                                                          ^
npm ERR! fatal error: too many errors emitted, stopping now [-ferror-limit=]
npm ERR! 33 warnings and 20 errors generated.
npm ERR! make[2]: *** [CMakeFiles/node-mdbx-native.dir/src/bindings.cc.o] Error 1
npm ERR! make[1]: *** [CMakeFiles/node-mdbx-native.dir/all] Error 2
npm ERR! make: *** [all] Error 2
npm ERR! ERR! OMG Process terminated: 2

**Comment by SergeyFromHell** [comment]
@rizkyramadhan Could you try 0.3.0 version?
I added -std=c++17 flag. But I can't test it on Mac, I dont have it.

**Comment by rizkyramadhan** [comment]
> % npm run platform i node-mdbx

> base@1.0.0 platform
> npm -w=platform "i" "node-mdbx"

npm ERR! code 1
npm ERR! path /Users/riz/Documents/base/node_modules/node-mdbx
npm ERR! command failed
npm ERR! command sh -c node build.js
npm ERR! [
npm ERR!   '/Users/riz/.fnm/node-versions/v16.4.0/installation/bin/node',
npm ERR!   '/Users/riz/Documents/base/node_modules/.bin/cmake-js',
npm ERR!   'rebuild'
npm ERR! ]
npm ERR! Not searching for unused variables given on the command line.
npm ERR! -- The C compiler identification is AppleClang 12.0.5.12050022
npm ERR! -- The CXX compiler identification is AppleClang 12.0.5.12050022
npm ERR! -- Detecting C compiler ABI info
npm ERR! -- Detecting C compiler ABI info - done
npm ERR! -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
npm ERR! -- Detecting C compile features
npm ERR! -- Detecting C compile features - done
npm ERR! -- Detecting CXX compiler ABI info
npm ERR! -- Detecting CXX compiler ABI info - done
npm ERR! -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
npm ERR! -- Detecting CXX compile features
npm ERR! -- Detecting CXX compile features - done
npm ERR! -- Configuring done
npm ERR! -- Generating done
npm ERR! -- Build files have been written to: /Users/riz/Documents/base/node_modules/node-mdbx/build
npm ERR! [ 16%] Building C object CMakeFiles/node-mdbx-native.dir/deps/mdbx/mdbx.c.o
npm ERR! [ 33%] Building CXX object CMakeFiles/node-mdbx-native.dir/src/bindings.cc.o
npm ERR! [ 50%] Building CXX object CMakeFiles/node-mdbx-native.dir/src/cpp_dbi.cc.o
npm ERR! [ 66%] Building CXX object CMakeFiles/node-mdbx-native.dir/src/cpp_mdbx.cc.o
npm ERR! info TOOL Using Unix Makefiles generator.
npm ERR! info CMD CLEAN
npm ERR! info RUN [
npm ERR! info RUN   'cmake',
npm ERR! info RUN   '-E',
npm ERR! info RUN   'remove_directory',
npm ERR! info RUN   '/Users/riz/Documents/base/node_modules/node-mdbx/build'
npm ERR! info RUN ]
npm ERR! info CMD CONFIGURE
npm ERR! info RUN [
npm ERR! info RUN   'cmake',
npm ERR! info RUN   '/Users/riz/Documents/base/node_modules/node-mdbx',
npm ERR! info RUN   '--no-warn-unused-cli',
npm ERR! info RUN   '-G',
npm ERR! info RUN   'Unix Makefiles',
npm ERR! info RUN   '-DCMAKE_JS_VERSION=6.1.4',
npm ERR! info RUN   '-DCMAKE_BUILD_TYPE=Release',
npm ERR! info RUN   '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/riz/Documents/base/node_modules/node-mdbx/build/Release',
npm ERR! info RUN   '-DCMAKE_JS_INC=/Users/riz/.cmake-js/node-arm64/v16.4.0/include/node',
npm ERR! info RUN   '-DCMAKE_JS_SRC=',
npm ERR! info RUN   '-DNODE_RUNTIME=node',
npm ERR! info RUN   '-DNODE_RUNTIMEVERSION=16.4.0',
npm ERR! info RUN   '-DNODE_ARCH=arm64',
npm ERR! info RUN   '-DCMAKE_CXX_FLAGS=-D_DARWIN_USE_64_BIT_INODE=1 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DBUILDING_NODE_EXTENSION',
npm ERR! info RUN   '-DCMAKE_SHARED_LINKER_FLAGS=-undefined dynamic_lookup'
npm ERR! info RUN ]
npm ERR! CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
npm ERR!   Compatibility with CMake < 2.8.12 will be removed from a future version of
npm ERR!   CMake.
npm ERR! 
npm ERR!   Update the VERSION argument <min> value or use a ...<max> suffix to tell
npm ERR!   CMake that the project does not need compatibility with older versions.
npm ERR! 
npm ERR! 
npm ERR! CMake Warning (dev):
npm ERR!   Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
npm ERR!   --help-policy CMP0042" for policy details.  Use the cmake_policy command to
npm ERR!   set the policy and suppress this warning.
npm ERR! 
npm ERR!   MACOSX_RPATH is not specified for the following targets:
npm ERR! 
npm ERR!    node-mdbx-native
npm ERR! 
npm ERR! This warning is for project developers.  Use -Wno-dev to suppress it.
npm ERR! 
npm ERR! info CMD BUILD
npm ERR! info RUN [
npm ERR! info RUN   'cmake',
npm ERR! info RUN   '--build',
npm ERR! info RUN   '/Users/riz/Documents/base/node_modules/node-mdbx/build',
npm ERR! info RUN   '--config',
npm ERR! info RUN   'Release'
npm ERR! info RUN ]
npm ERR! /Users/riz/Documents/base/node_modules/node-mdbx/src/cpp_mdbx.cc:23:44: error: conversion from 'Napi::Number' to 'intptr_t' (aka 'long') is ambiguous
npm ERR!         pageSize = options.Get("pageSize").ToNumber();
npm ERR!                    ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:352:4: note: candidate function
npm ERR!    operator int32_t()
npm ERR!    ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:354:4: note: candidate function
npm ERR!    operator uint32_t()
npm ERR!    ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:356:4: note: candidate function
npm ERR!    operator int64_t()
npm ERR!    ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:358:4: note: candidate function
npm ERR!    operator float()
npm ERR!    ^
npm ERR! /Users/riz/Documents/base/node_modules/node-addon-api/napi.h:360:4: note: candidate function
npm ERR!    operator double()
npm ERR!    ^
npm ERR! 1 error generated.
npm ERR! make[2]: *** [CMakeFiles/node-mdbx-native.dir/src/cpp_mdbx.cc.o] Error 1
npm ERR! make[1]: *** [CMakeFiles/node-mdbx-native.dir/all] Error 2
npm ERR! make: *** [all] Error 2
npm ERR! ERR! OMG Process terminated: 2

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/riz/.npm/_logs/2021-07-02T06_43_30_503Z-debug.log

**Comment by rizkyramadhan** [comment]
It's much shorter now, but still don't have a clue what's gone wrong. Sorry for slow response >.<

**Comment by SergeyFromHell** [comment]
Possibly fixed. Try 0.3.1.

**Comment by rizkyramadhan** [comment]
Congrats!

-> % npm i node-mdbx

added 55 packages, and audited 1422 packages in 14s

101 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
