### ISSUE TITLE
First key do not returns first key indeed

### ISSUE THREAD

**Issue by anuragvohraec** [SergeyFromHell/node-mdbx#7]
Hi Team,

I have written this code , which basically stores three numbers in the DB (1,8,10) and then tries to print them one by one.
I call `dbi.first()` to get the first key, however the code below does not returns first key, instead creates an infinite loop.

Please assist whats wrong?

```
const MDBX = require("node-mdbx");
const db = new MDBX({
    path: '/tmp/test_db',
    maxDbs: 5,
    syncMode: 'safeNoSync',
    readOnly: false,
    pageSize: 65536,
    keyMode: 'string',
    valueMode: 'buffer',
  });
  
  const result = db.transact(txn => {
    const dbi = txn.getDbi('main');

    { 
        //insert
        let buff = Buffer.alloc(8);
        buff.writeDoubleBE(10.2);
        dbi.put(buff, '10');
     }
    
   {
      //insert
      let buff = Buffer.alloc(8);
      buff.writeDoubleBE(1);
      dbi.put(buff, '1');
   }

   {
    //insert
    let buff = Buffer.alloc(8);
    buff.writeDoubleBE(8);
    dbi.put(buff, '8');
    }
  
   {
    //reading first key
    let key = dbi.first();
     
    let value = dbi.get(key);
    console.log(String(value));
    while(key){
        key=dbi.next(key);
        if(key){
            let b = Buffer.alloc(8,key);
            console.log("found key:",b.readDoubleBE(),"found value:", String(dbi.get(key)));
        }
    }
   }
  });
```

**Comment by SergeyFromHell** [comment]
Hello, @anuragvohraec .
There are some inconsistences with the code:
1. keyMode = 'string' is used, so keys will be converted to strings before storing them
2. inserted keys are:
  10.2 -> <Buffer 40 24 66 66 66 66 66 66>
  1 -> <Buffer 3f f0 00 00 00 00 00 00>
  8 -> <Buffer 40 20 00 00 00 00 00 00>
The database stores keys as "buffers" in lexicographical order. So floating point numbers will not save their order after such a transformation chain: float -> buffer(through writeDoubleBE) -> string -> buffer (throw buffer.toString).

Another problem here is that the is a lossy transformation, so there is an infinite loop.

If you want to store floating point keys, then you can try some order-preserving encoder such as:
https://www.npmjs.com/package/bytewise

**Comment by SergeyFromHell** [comment]
Here is a working equivalent:
`const MDBX = require('../lib/binding');
const { encode, decode } = require('bytewise');

const db = new MDBX({
  path: '/tmp/test_db',
  maxDbs: 5,
  syncMode: 'safeNoSync',
  readOnly: false,
  pageSize: 65536,
  keyMode: 'buffer',
  valueMode: 'string',
});

const result = db.transact(txn => {
  const dbi = txn.getDbi('main');

  dbi.put(encode(10.2), '10');
  dbi.put(encode(1), '1');
  dbi.put(encode(8), '8');

  for (let key = dbi.first(); key != null; key = dbi.next(key)) {
    console.log('key:', decode(key), 'value:', dbi.get(key));
  };
});`
