### ISSUE TITLE
DupSort support

### ISSUE THREAD

**Issue by LogvinovLeon** [SergeyFromHell/node-mdbx#8]
Do I understand it right, that this library doesn't support MDBX DupSort feature and DB flags in general (`MDBX_DUPFIXED`)?

**Comment by SergeyFromHell** [comment]
Hello, @LogvinovLeon !
Yes, you are right. node-mdbx has only basic key-value functionality. Some low-level things MDBX can handle are not usually important for (any) JS library as its usage implies some low performance tolerance. Some could be "emulated" by user (with performance and/or simplicity penalty).

But any feature requests are welcome.

**Comment by LogvinovLeon** [comment]
Hi @SergeyFromHell
Totally understand. My case is that I have a DB from an ethereum node (erigon) and I want to read some data from it and this data is stored in a bucket that is dupsorted. And with current state this is not doable, but I was able to implement it quite fast on my side. Unfortunately this could not be "emulated" by user as I'm only getting a first value for the key and I need to go down to C++ level and work wit cursor operations.
